services:
  backend:
    build: ./Henyway-Backend
    container_name: ecom-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./Henyway-Frontend
    container_name: ecom-frontend
    ports:
      - "3000:80"